//
// Created by Wojtek on 31/05/2020.
//

#ifndef FISH_SYMBOLTYPE_H
#define FISH_SYMBOLTYPE_H

enum class SymbolType {
    AddExpressionType,
    AddOperatorType,
    AliasStatementType,
    AndExpressionType,
    ArgumentType,
    ArgumentListType,
    ArithmeticExpressionType,
    ArraySubscriptType,
    AssignExpressionType,
    AssignOperatorType,
    AssignStatementType,
    BlockInstructionType,
    BoolType,
    ClassBodyType,
    ClassBodyStatementType,
    ClassDefinitionType,
    CompoundStatementType,
    ConditionalExpressionType,
    ControlStatementType,
    DefaultType,
    DeleteStatementType,
    ExpressionType,
    ExpressionStatementType,
    FileType,
    FilePartType,
    ForeachStatementType,
    ForiStatementType,
    ForStatementType,
    FunctionCallType,
    FunctionDefinitionType,
    IfStatementType,
    ImportStatementType,
    MemberDefinitionType,
    MultiplyExpressionType,
    MultiplyOperatorType,
    NewExpressionType,
    NewStatementType,
    OrExpressionType,
    ParameterType,
    ParameterListType,
    RelativeExpressionType,
    RelativeOperatorType,
    SimpleStatementType,
    StatementType,
    TermType,
    TypeType,
    UnaryNotType,
    UnarySignType,
    UnsignedIntTermType,
    WhileStatementType,
    BaseType,
};

#endif //FISH_SYMBOLTYPE_H
